sudo: required
language: generic

services:
  - docker

script:
  - docker build -t "$DOCKER_ID"/php-apache-laravel:"$PHP_VERSION"_"$NODE_VERSION" --build-arg PHP_VERSION="$PHP_VERSION" --build-arg NODE_VERSION="$NODE_VERSION" .

after_script:
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push image to dockerhub
  - docker push "$DOCKER_ID"/php-apache-laravel:"$PHP_VERSION"_"$NODE_VERSION"